Create dnslookupcheck.py
Netuitive/netuitive-diamond pull request #50
Opened 2018-03-28 22:22 UTC by jasonNetuitive

new dnslookup check collector.

2018-03-29 11:16 UTC, Grumblesmith requested changes
The default_config and default_config_help need corrections.

2018-03-29 12:15 UTC, TheConnMan commented on src/collectors/dnslookupcheck/dnslookupcheck.py
> +        for x in self.config['dnsAddressList']:
`x` is not a descriptive variable name. I recommend changing to something like `dnsAddress`.

2018-04-02 18:12 UTC, Grumblesmith approved these changes

2018-04-02 18:14 UTC, Grumblesmith commented
@TheConnMan I've updated the variable names, default_config and default_config_help sections, and shortened several lines which overran the PEP 8 line length limit. Could you take another look?

2018-04-02 18:15 UTC, TheConnMan approved these changes

2018-04-02 18:15 UTC, TheConnMan commented
I was already looking at it.

2018-04-02 18:15 UTC, Grumblesmith commented
Thanks!

2018-04-02 18:16 UTC, merged