Feature/docker uptime
Netuitive/netuitive-diamond pull request #92
Opened 2018-11-27 13:04 UTC by yadima

Added netuitivedocker collector uptime feature.

2018-11-27 13:25 UTC, TheConnMan requested changes

2018-11-27 13:25 UTC, TheConnMan commented on src/collectors/netuitivedocker/netuitivedocker.py
> +        def print_uptime(cc):
`print_uptime` is an odd name for a method which collects uptime. What about `collect_uptime`?

2018-11-27 13:25 UTC, TheConnMan commented on src/collectors/netuitivedocker/netuitivedocker.py
> +            for i in cc.containers():
Collecting all containers again for every collection my adversely affect collection time. Why not perform this logic inside the existing container collection loop?

2018-11-27 13:25 UTC, TheConnMan commented on src/collectors/netuitivedocker/netuitivedocker.py
> +                    if 'year' in i['Status']:
This is an inaccurate representation of how long the container has been up. You'll only ever get the largest unit of how long the container has been up.

I recommend using the `Created` property on `i` which is the epoch time that the container was created. Subtract it from the current time to get an uptime accurate to the second.

2018-11-27 14:16 UTC, Grumblesmith commented on src/collectors/netuitivedocker/netuitivedocker.py
> +                    if 'year' in i['Status']:
Is that property updated if the container is stopped then started?

2018-11-27 15:41 UTC, TheConnMan commented on src/collectors/netuitivedocker/netuitivedocker.py
> +                    if 'year' in i['Status']:
Good point, probably not. Even better is `cc.inspect_container(i['Id'])['State']['StartedAt']`.

2018-11-29 00:27 UTC, yadima commented on src/collectors/netuitivedocker/netuitivedocker.py
> +        def print_uptime(cc):
Done. Changed the name to collect_uptime in the last commit :)

2018-11-29 00:30 UTC, yadima commented on src/collectors/netuitivedocker/netuitivedocker.py
> +            for i in cc.containers():
Done changes in the last commit. Moved the collect_uptime call inside the exisiting loop at the bottom.

2018-11-29 00:33 UTC, yadima commented on src/collectors/netuitivedocker/netuitivedocker.py
> +                    if 'year' in i['Status']:
Done changes in the last commit. Rewritten the code with cc.inspect_container method.

2018-11-29 13:16 UTC, TheConnMan approved these changes

2018-11-29 16:21 UTC, Grumblesmith approved these changes

2018-11-30 17:28 UTC, merged